services:
  - type: web
    name: minecraft-vscode
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 30
    autoDeploy: true
    disk:
      name: minecraft-data
      mountPath: /home/coder/minecraft
      sizeGB: 1
