services:
  - type: web
    name: full-root-vscode
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 30
    autoDeploy: true
    disk:
      name: root-workspace
      mountPath: /home/coder/workspace
      sizeGB: 1
