services:
  - type: web
    name: rdp-vscode-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 30
    autoDeploy: true
    disk:
      name: rdp-desktop-data
      mountPath: /home/coder
      sizeGB: 1
